# Generated by Django 5.0.2 on 2025-07-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_shopping', '0002_category_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total',
        ),
    ]
